### ISSUE TITLE
Last frame lost after noLoop() in OpenGL renderer

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#478]
In the following code:

```java
int frame0;

void setup() {
  fullScreen(P2D);  
  noLoop();
}

void draw() {
  background(random(255), random(255), random(255));
  translate(width/2, height/2);
  rotate(random(TWO_PI));
  rect(-100, -100, 200, 200);
  println(frameCount - frame0);
  if (60 < frameCount - frame0) {
    println("stop");
    noLoop();
  }
}

void mousePressed() {
  println("start");
  loop();  
  frame0 = frameCount;
}
```

the rectangle is only visible while looping, after noLoop() it disappears. This does not happen with the default renderer.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/23d5d9083a1b01a5bbe79f9c3caab54ccac1752e

**Comment by RobbertC5** [comment]
This bug is still present.

```
void settings(){
  fullScreen(P2D);
}
 
void setup(){
  //frameRate(0.5f);
  background(255,0,0);
}

void draw(){
  background(0);
  fill(0,0,255);
  textSize(50*displayDensity);
  textAlign(CENTER,CENTER);
  text(String.valueOf(frameCount), 0,0, width, height);
  if(frameCount>=120){
    noLoop();
  }
}
```

The counter will run to 120 and then go back to 118.
When noLoop() is invoked in the first frame (instead of the 120th), the screen will reset to the red screen that was drawn in setup(). This happens even with a very low frameRate. The default renderer works as expected.
